# Generated by Django 5.1.4 on 2025-02-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_contact_enquiry_additional_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='contact_enquiry',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
