# Generated by Django 5.1.4 on 2025-02-11 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_index_project_alter_contact_enquiry_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index_project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='index_project',
            name='link',
        ),
        migrations.AddField(
            model_name='index_project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='index_project',
            name='client_name',
            field=models.CharField(default='Unknown Client', max_length=100),
        ),
        migrations.AddField(
            model_name='index_project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index_project',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='index_project',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='index_project',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='index_project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='index_project',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='index_project',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AlterField(
            model_name='index_project',
            name='title',
            field=models.CharField(default='Untitled Project', max_length=200),
        ),
    ]
