# Generated by Django 5.1.4 on 2025-02-11 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_index_project_image_remove_index_project_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_project',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='index_project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='index_project',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='index_project',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
