# Generated by Django 5.1.4 on 2025-02-11 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_index_project_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index_project',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='index_project',
            name='images',
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='main.index_project')),
            ],
        ),
    ]
