# Generated by Django 5.1.4 on 2025-02-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='app\\static\\main\\img\\Achievement.png', upload_to='product_images/'),
        ),
    ]
